Wek files issues
minova-afis/aero.minova.core.application.system pull request #172
Opened 2021-08-04 07:46 UTC by weber-minova

closes #162
closes #159 
closes #163

2021-08-04 09:17 UTC, splitcells requested changes

2021-08-04 09:17 UTC, splitcells commented on aero.minova.core.application.system.service/src/main/java/aero/minova/core/application/system/controller/FilesController.java
> +		File zipDirectoryStructure = new File(zipDataName.substring(0, zipDataName.lastIndexOf('/')));
getParent() und keine String-Operation bitte. 🧐

2021-08-04 09:17 UTC, splitcells commented on aero.minova.core.application.system.service/src/main/java/aero/minova/core/application/system/controller/FilesController.java
> +		File zipFile = new File(zipDataName + ".zip");
`path.getParent().resolve(path.getFileName() + ".zip")` 🧐

2021-08-04 09:17 UTC, splitcells commented on aero.minova.core.application.system.service/src/main/java/aero/minova/core/application/system/controller/FilesController.java
> +				File newFile = destDirName.resolve(zippedFileEntry).toFile();
👍

2021-08-04 09:17 UTC, splitcells commented on aero.minova.core.application.system.service/src/main/java/aero/minova/core/application/system/service/FilesService.java
> +	static CustomLogger customLogger = new CustomLogger();
Warum brauchen wir das?
Zudem widerspricht es dem geandken der Dependnecy Injection. 🕵️

2021-08-04 09:17 UTC, splitcells commented on aero.minova.core.application.system.service/src/main/java/aero/minova/core/application/system/controller/FilesController.java
> +	 * @param log
Doku! 🥳

2021-08-04 09:17 UTC, splitcells commented on aero.minova.core.application.system.service/src/test/java/aero/minova/core/application/system/controller/FilesControllerTest.java
> +		testSubject.createZip(serviceFolder);
Übersichtlichere Tests 🥳

2021-08-04 09:17 UTC, splitcells commented on aero.minova.core.application.system.service/src/test/java/aero/minova/core/application/system/controller/FilesControllerTest.java
> +		Mockito.when(authentication.getName()).thenReturn("test");
Nutzer in Tests! 🥳

2021-08-04 09:54 UTC, weber-minova commented on aero.minova.core.application.system.service/src/main/java/aero/minova/core/application/system/controller/FilesController.java
>  	public @ResponseBody byte[] getFile(@RequestParam String path) throws Exception {
ja, aber durch #163 werden sie nun in den Internal Ordner geschrieben.
Deshalb habe ich die Methode getZip geschrieben, welche fast genauso wie getHash ist, nur eben für die zips

2021-08-04 10:01 UTC, splitcells commented on aero.minova.core.application.system.service/src/main/java/aero/minova/core/application/system/controller/FilesController.java
>  	public @ResponseBody byte[] getFile(@RequestParam String path) throws Exception {
Wir sollten aber die Rückwärts-Kompatibilität einfach brechen.
Wenn also eine Zip-Datei über `files/read` angefordert wird,
sollte man das entsprechend umleiten.

2021-08-20 13:04 UTC, splitcells requested changes

2021-08-20 13:04 UTC, splitcells commented on aero.minova.core.application.system.service/src/test/java/aero/minova/core/application/system/controller/BaseTest.java
> +	public static void cleanInternalFolder() throws Exception {
Wäre es nicht sinnvoller für die Tests aero_minova_core_application_root_path auf ./target zu setzen?
Wir haben ja eine `test/resources/application.properties`.

2021-08-20 13:23 UTC, splitcells commented on aero.minova.core.application.system.service/src/main/java/aero/minova/core/application/system/controller/FilesController.java
> +				createZip(path.subpath(files.getSystemFolder().getNameCount(), path.getNameCount()));
Bitte Index-Operationen vermeiden.
Ich glaube dass `files.getSystemFolder.toAbsolutePath().relativize​(path.toAbsolutePath())`, dass gleiche ist.

2021-08-24 08:50 UTC, merged