#220 wek prüfprozeduren nach transaktion ausführen
minova-afis/aero.minova.core.application.system pull request #224
Opened 2021-11-23 11:33 UTC by weber-minova

closes #220

2021-12-01 10:48 UTC, splitcells requested changes

2021-12-01 10:48 UTC, splitcells commented on aero.minova.core.application.system.service/src/main/java/aero/minova/core/application/system/controller/XSqlProcedureController.java
> +				if (row.getValues().size() != 0 && row.getValues().get(1) != null) {
`get(1)` impliziert `size() >= 2`

2021-12-01 10:48 UTC, splitcells commented on aero.minova.core.application.system.service/src/main/java/aero/minova/core/application/system/controller/XSqlProcedureController.java
> +			List<XTable> xtables = new ArrayList<>();
Ich denke ein name wie checks oder sowas wäre besser.

2021-12-01 10:48 UTC, splitcells commented on aero.minova.core.application.system.service/src/main/java/aero/minova/core/application/system/controller/XSqlProcedureController.java
> +					XTable followUpTable = new XTable();
Wäre das auch nicht sowas wie ein check?
Also bspw. followUpCheck?

2021-12-01 10:48 UTC, splitcells commented on aero.minova.core.application.system.service/src/main/java/aero/minova/core/application/system/controller/XSqlProcedureController.java
> +		Table sqlRequest = new Table();
priviligeRequest oder so wäre besser.

2021-12-01 10:48 UTC, splitcells commented on aero.minova.core.application.system.service/src/main/java/aero/minova/core/application/system/controller/XSqlProcedureController.java
> +						xtables.add(followUpTable);
Müsste man hier nicht jeweils eine nue followUpTable erzeugen,
bzw. die Erzeugung am Anfang dieser for-Schleife verschieben?

2021-12-01 10:48 UTC, splitcells commented on aero.minova.core.application.system.service/src/test/java/aero/minova/core/application/system/controller/XSqlProcedureControllerTest.java
> -	public void testFindValueValid() {
Eigentlich wollten wird das über JSON-Dateien machen ^^'

2021-12-01 10:48 UTC, splitcells commented on aero.minova.core.application.system.app/doc/adoc/table-index.adoc
> -* link:xtcasError.adoc[]
Bitte die Changelog diesbezüglich aktualisieren.

2021-12-01 15:03 UTC, weber-minova commented on aero.minova.core.application.system.service/src/main/java/aero/minova/core/application/system/controller/XSqlProcedureController.java
>  		} catch (Exception e) {
Sollte das auch im SqlProcedureController und SqlViewController geändert werden oder nur da?

2021-12-06 08:46 UTC, splitcells approved these changes

2021-12-06 09:40 UTC, merged