Wek #240 fehlermeldung für wfc anpassen
minova-afis/aero.minova.core.application.system pull request #244
Opened 2022-01-14 06:40 UTC by weber-minova

closes #240

2022-01-14 08:50 UTC, splitcells requested changes

2022-01-14 08:50 UTC, splitcells commented on aero.minova.core.application.system.service/doc/adoc/api-error.adoc
> +Im letzten Value steht immer die DEFAULT Übersetzung der Fehlermeldung.
In der letzten Spalte namens `DEFAULT` steht immer die Standard-Übersetzung der Fehlermeldung.

2022-01-14 08:50 UTC, splitcells commented on aero.minova.core.application.system.service/doc/adoc/api-error.adoc
> +Falls die Default-Nachricht einen oder mehrere Inputparameter benötigt, folgen weitere String-Values, welche die einzelnen Parameter enthalten.
Hat die Standardübersetzhung jemals Parameter und wenn ja, wieso?

2022-01-14 08:50 UTC, splitcells commented on aero.minova.core.application.system.service/doc/adoc/api-error.adoc
> +Falls die Default-Nachricht einen oder mehrere Inputparameter benötigt, folgen weitere String-Values, welche die einzelnen Parameter enthalten.
Zudem sollte man es im Beispiel anzeigen,
wenn man es wirklich hat.

2022-01-14 08:50 UTC, splitcells commented on aero.minova.core.application.system.service/doc/adoc/api-error.adoc
> +Die Columns dazwischen sind Parameter, welche in der Original-Fehlermeldung mit '@' gekennzeichnet waren.
Die Columns zwischen `International Message` und `Default` sind...

2022-01-14 08:50 UTC, splitcells commented on aero.minova.core.application.system.service/doc/adoc/api-error.adoc
> +Die Columns dazwischen sind Parameter, welche in der Original-Fehlermeldung mit '@' gekennzeichnet waren.
`Original-Fehlermeldung mit '@' gekennzeichnet waren.`
-> `Original-Fehlermeldung mit '@[Datentyp]' gekennzeichnet waren.`

2022-01-14 08:50 UTC, splitcells commented on aero.minova.core.application.system.service/doc/adoc/api-error.adoc
> +Diese sind in der Regel:
Folgende Datentypen existieren...
(Also der Verweis auf Datentyp ist wichtig bzw. welches Wort man dafür auch immer verwendet
damit ein klarer/expliziter Bezug existiert.)

2022-01-14 08:50 UTC, splitcells commented on aero.minova.core.application.system.service/doc/adoc/api-error.adoc
> +Falls die Default-Nachricht einen oder mehrere Inputparameter benötigt, folgen weitere String-Values, welche die einzelnen Parameter enthalten.
Ich bin eher der Meinung, dass die Standard-Übersetzung für sich vollständig sein sollte,
da dies eine Art-Backup/Notfallübersetzung ist.

2022-01-14 08:50 UTC, splitcells commented on aero.minova.core.application.system.service/doc/adoc/api-error.adoc
> +Die Werte in den dazugehörigen Values sind die Strings, welche nach dem @d|d.iso|f|f.iso|s|p|i-Parameter kommen.
Verstehe den Satz nicht wirklich.

2022-01-14 09:30 UTC, weber-minova commented on aero.minova.core.application.system.service/doc/adoc/api-error.adoc
> +Falls die Default-Nachricht einen oder mehrere Inputparameter benötigt, folgen weitere String-Values, welche die einzelnen Parameter enthalten.
> Ich bin eher der Meinung, dass die Standard-Übersetzung für sich vollständig sein sollte, da dies eine Art-Backup/Notfallübersetzung ist.

Hast Recht. Ich ändere das

2022-01-24 08:51 UTC, splitcells requested changes

2022-01-24 08:51 UTC, splitcells commented on aero.minova.core.application.system.service/src/main/java/aero/minova/core/application/system/ControllerExceptionHandler.java
> +			outputTable = handleGenericErrorMessage(outputTable, errorMessage);
Eine Default-Übersetzung gibt es für diesen Fall nicht, richtig?

2022-01-24 08:51 UTC, splitcells commented on aero.minova.core.application.system.service/doc/adoc/api-error.adoc
> +In die Zeile wird der String-Value dann eingefügt,
Muss es nicht Spalte heißen?

2022-01-26 08:02 UTC, weber-minova commented on aero.minova.core.application.system.service/src/main/java/aero/minova/core/application/system/ControllerExceptionHandler.java
> +			outputTable = handleGenericErrorMessage(outputTable, errorMessage);
Nein, gibt es nicht.

2022-02-04 09:37 UTC, splitcells requested changes
Bitte changelog anpassen,
ansonsten 👌

2022-02-04 10:57 UTC, splitcells approved these changes

2022-02-04 10:57 UTC, splitcells commented on CHANGELOG.adoc
> +Fehlermeldungen können nun auf zwei verschiedene Arten verarbeitet und dargestellt werden.
In Zukunft die Issue-Number angeben und es etwas detailierter beschreiben
(man kann auch auf die Doku verweisen).
In diesem Fall bspw.: Fehlermeldungen von SQL-Prozeduren so ausgeben,
dass Clients diese übersetzen können.

2022-02-04 10:57 UTC, merged